---
pipeline:
  prep:
    image: library/debian:unstable
    commands:
      - apt-get update
      - apt-get -y remove man-db
      - apt-get -y install devscripts git-buildpackage locales
      - mk-build-deps --install -t'apt-get -y'
      - mkdir build
      - cd build
      - cmake ..
      - make
      - LANG="en_US.UTF-8" ./outcurses-tester
---
kind: signature
hmac: 7c153f11139fbdd384e25faf796e2b51c7ee232247e537e9125a2df95e777a37

...
